dim: sparse: show an error message if baseline build fails
In case the baseline build by 'dim sparse' fails, dim exits silently and
returns a success error value, leaving users without a hint about what is
going on:

  $ dim sparse drm-misc/drm-misc-next..drm-misc-next
  Sparse version: 0.6.4
  $ echo $?
  0
  $

At least show an error message when this happens.

Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>

---

Returning non-zero would be nice but seems non-trivial to do based on
_restore_head_on_exit, so leave this for the future.

diff --git a/dim b/dim
--- a/dim
+++ b/dim
@@ -2079,7 +2079,10 @@ function dim_sparse
 	commits=( $(git rev-list --reverse $range) )
 	git checkout --detach  ${commits[0]}~ > /dev/null 2>&1
 	make olddefconfig > /dev/null 2>&1
-	make -j$(nproc) drivers/gpu/drm/ > /dev/null 2>&1
+	if ! make -j$(nproc) drivers/gpu/drm/ > /dev/null 2>&1; then
+	   echo "Failed building baseline commit $(git log -n 1 --pretty=tformat:'%h ("%s")')" 2>&1
+	   false
+	fi
 
 	if [ "$fast" == 1 ]; then
 		prev_rev="${commits[0]}~"
